// AUTO-GENERATED by the FapForge bundler. DO NOT EDIT.
#pragma once
#include <stdint.h>
#include "../../libs/engine/assets/assets.h"

namespace Game { namespace Assets {

extern const Engine::Texture     BRICK;
extern const Engine::Texture     STONE;
extern const Engine::Texture     DOOR;
extern const Engine::SpriteSheet COIN;
extern const Engine::SpriteSheet BULLET;
extern const Engine::SpriteSheet PISTOL;
extern const Engine::SpriteSheet SMG_ICON;
extern const Engine::SpriteSheet SHOTGUN;
extern const Engine::SpriteSheet KEY;
extern const Engine::SpriteSheet GOAL;
extern const Engine::SpriteSheet POTION;
extern const Engine::SpriteSheet ARMOR;
extern const Engine::SpriteSheet TORCH;
extern const Engine::SpriteSheet CHEST;
extern const Engine::SpriteSheet SKELETON_FRONT;
extern const Engine::SpriteSheet SKELETON_FRONT_LEFT;
extern const Engine::SpriteSheet SKELETON_RIGHT;
extern const Engine::SpriteSheet SKELETON_BACK_LEFT;
extern const Engine::SpriteSheet SKELETON_BACK;

inline const Engine::Texture* const WALL_TEXTURES[] = {
    nullptr,   // 0 = empty
    &BRICK,  // 1
    &STONE,  // 2
    &DOOR,  // 3
};
constexpr int WALL_TEXTURE_COUNT = 4;

}} // namespace Game::Assets
